document.addEventListener("DOMContentLoaded",()=>{const a=document.getElementById("product-list"),b=document.getElementById("product-form"),c=document.getElementById("add-product-btn"),d=document.getElementById("add-product-section"),e=document.getElementById("cart-btn"),f=document.getElementById("cart-modal"),g=document.getElementById("cart-items"),h=document.getElementById("cart-count"),i=document.getElementById("checkout-btn"),j=document.getElementById("notification");let k=JSON.parse(localStorage.getItem("cart"))||[];const l=()=>{h.textContent=k.length},m=()=>{a.innerHTML="";const b=JSON.parse(localStorage.getItem("products"))||[];b.forEach((b,c)=>{const d=document.createElement("div");d.classList.add("product-card"),d.innerHTML=`
    <img src="${b.image}" alt="${b.name}">
    <h3>${b.name}</h3>
    <p>R$ ${parseFloat(b.price).toFixed(2)}</p>
    <button class="btn-buy" data-index="${c}">Comprar</button>
    <button class="btn-delete" data-index="${c}">&times;</button>
`,a.appendChild(d)}),document.querySelectorAll(".btn-buy").forEach(a=>{a.addEventListener("click",a=>{o(a.target.dataset.index)})}),document.querySelectorAll(".btn-delete").forEach(a=>{a.addEventListener("click",a=>{r(a.target.dataset.index)})})},n=a=>{j.textContent=a,j.style.display="block",setTimeout(()=>{j.style.display="none"},3e3)},o=a=>{const b=JSON.parse(localStorage.getItem("products"))||[],c=b[a];k.push(c),localStorage.setItem("cart",JSON.stringify(k)),l(),n(`${c.name} adicionado ao carrinho!`)},p=()=>{g.innerHTML="";let a=0;k.forEach((b,c)=>{const d=document.createElement("div");d.innerHTML=`
    <p>${b.name} - R$ ${parseFloat(b.price).toFixed(2)}</p>
    <button class="btn-remove" data-index="${c}">Remover</button>
`,g.appendChild(d),a+=parseFloat(b.price)}),document.getElementById("cart-total").textContent=`R$ ${a.toFixed(2)}`,f.style.display="block",document.querySelectorAll(".btn-remove").forEach(a=>{a.addEventListener("click",a=>{q(a.target.dataset.index)})})},q=a=>{k.splice(a,1),localStorage.setItem("cart",JSON.stringify(k)),p(),l(),n("Item removido do carrinho!")},r=a=>{const b=prompt("Digite a senha para deletar o produto:");if("2115"===b){const b=JSON.parse(localStorage.getItem("products"))||[];b.splice(a,1),localStorage.setItem("products",JSON.stringify(b)),m(),n("Produto deletado com sucesso!")}else n("Senha incorreta! O produto n\xE3o foi deletado.")};document.getElementById("close-cart-btn").addEventListener("click",()=>{f.style.display="none"}),e.addEventListener("click",p),i.addEventListener("click",()=>{if(0===k.length)return void n("Seu carrinho est\xE1 vazio. Adicione produtos antes de finalizar a compra.");let a="Ol\xE1, gostaria de finalizar a compra com os seguintes itens:\n\n",b=0;k.forEach(c=>{a+=`- ${c.name}: R$ ${parseFloat(c.price).toFixed(2)}\n`,b+=parseFloat(c.price)}),a+=`\nTotal: R$ ${b.toFixed(2)}`;const c=encodeURIComponent(a);window.open(`https://wa.me/${"+5522998868822"}?text=${c}`,"_blank"),k=[],localStorage.setItem("cart",JSON.stringify(k)),l()}),b.addEventListener("submit",a=>{a.preventDefault();const c=document.getElementById("product-name").value,d=parseFloat(document.getElementById("product-price").value),e=document.getElementById("product-image");if(!c||isNaN(d)||0>=d)return void n("Por favor, insira um nome e um pre\xE7o v\xE1lido para o produto.");const f=new FileReader;f.onload=function(a){const e=a.target.result,f=JSON.parse(localStorage.getItem("products"))||[];f.push({name:c,price:d,image:e}),localStorage.setItem("products",JSON.stringify(f)),b.reset(),m(),n("Produto adicionado com sucesso!")},f.readAsDataURL(e.files[0])}),c.addEventListener("click",()=>{const a=prompt("Digite a senha para acessar a adi\xE7\xE3o de produtos:");"2115"===a?"none"===d.style.display||""===d.style.display?d.style.display="block":d.style.display="none":n("Senha incorreta! Voc\xEA n\xE3o tem permiss\xE3o para adicionar produtos.")}),m(),l()});